//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_TSPNET
{
    using System;
    using System.Collections.Generic;

    public partial class MediaItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MediaItems()
        {
            this.Persons = new HashSet<Persons>();
            this.DynamicProperties = new HashSet<DynamicProperties>();
            this.Date = DateTime.Now;
        }

        public int ItemId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
        public string Extension { get; set; }
        public bool IsPhoto { get; set; }
        public bool MarkedForDelete { get; set; }
        public bool PermanentDelete { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> EventsEventId { get; set; }

        public virtual Locations Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Persons> Persons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DynamicProperties> DynamicProperties { get; set; }
        public virtual Events Event { get; set; }
    }
}
