//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_TSPNET
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class ModelContainer : DbContext
    {
        private static ModelContainer context;
        public static ModelContainer GetContext()
        {
            if (context == null)
            {
                context = new ModelContainer();
            }
            return context;
        }
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<MediaItems> MediaItems { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<DynamicProperties> DynamicProperties { get; set; }
        public virtual DbSet<Events> Events { get; set; }
    }
}
